[package]
name = "tgs_services"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
derive_builder = "0.12"
ropey = "1.6"
unicode-width = "0.1"

anyhow = "1"
thiserror = "1"
